name: whack
description: A production-ready Hacker News client built with Flutter and GetX.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.11.3 <4.0.0"
  flutter: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter

  # State management + DI + routing
  get: ^4.7.3

  # Network
  dio: ^5.9.2

  # JSON
  json_annotation: ^4.11.0

  # Utilities
  url_launcher: ^6.3.2
  intl: ^0.20.2
  share_plus: ^12.0.1

  # UI / Rendering
  flutter_html: ^3.0.0

  # Env config
  flutter_dotenv: ^6.0.0
  shadcn_ui: ^0.52.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Testing
  build_runner: ^2.13.1

  # Code generation
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
